; Fledge custom Japanese NSIS strings (shorter = less cramped on MUI pages)
; Keep UTF-8 (Tauri rewrites with BOM on bundle).

LangString addOrReinstall ${LANG_JAPANESE} "コンポーネントの追加・再インストール"
LangString alreadyInstalled ${LANG_JAPANESE} "既にインストールされています"
LangString alreadyInstalledLong ${LANG_JAPANESE} "${PRODUCTNAME} ${VERSION} は既にインストールされています。$\n操作を選んで「次へ」を押してください。"
LangString appRunning ${LANG_JAPANESE} "{{product_name}} が起動中です。終了してから再度お試しください。"
LangString appRunningOkKill ${LANG_JAPANESE} "{{product_name}} が起動中です。$\n「OK」で終了して続行します。"
LangString chooseMaintenanceOption ${LANG_JAPANESE} "実行するメンテナンスを選んでください。"
LangString choowHowToInstall ${LANG_JAPANESE} "${PRODUCTNAME} のインストール方法を選んでください。"
LangString createDesktop ${LANG_JAPANESE} "デスクトップショートカットを作成する"
LangString dontUninstall ${LANG_JAPANESE} "アンインストールしない"
LangString dontUninstallDowngrade ${LANG_JAPANESE} "アンインストールしない（ダウングレードにはアンインストールが必要です）"
LangString failedToKillApp ${LANG_JAPANESE} "{{product_name}} を終了できませんでした。手動で終了してから再度お試しください。"
LangString installingWebview2 ${LANG_JAPANESE} "WebView2 をインストールしています…"
LangString newerVersionInstalled ${LANG_JAPANESE} "新しいバージョンの ${PRODUCTNAME} が既に入っています。$\n旧版の導入は推奨されません。操作を選んで「次へ」を押してください。"
LangString older ${LANG_JAPANESE} "旧"
LangString olderOrUnknownVersionInstalled ${LANG_JAPANESE} "バージョン $R4 の ${PRODUCTNAME} がインストールされています。$\n先にアンインストールすることを推奨します。操作を選んで「次へ」を押してください。"
LangString silentDowngrades ${LANG_JAPANESE} "このインストーラーではダウングレードできません。GUI インストーラーを使ってください。$\n"
LangString unableToUninstall ${LANG_JAPANESE} "アンインストールできません。"
LangString uninstallApp ${LANG_JAPANESE} "${PRODUCTNAME} をアンインストールする"
LangString uninstallBeforeInstalling ${LANG_JAPANESE} "インストール前にアンインストールする"
LangString unknown ${LANG_JAPANESE} "不明"
LangString webview2AbortError ${LANG_JAPANESE} "WebView2 のインストールに失敗しました。再起動してやり直してください。"
LangString webview2DownloadError ${LANG_JAPANESE} "エラー: WebView2 のダウンロードに失敗しました - $0"
LangString webview2DownloadSuccess ${LANG_JAPANESE} "WebView2 ブートストラップのダウンロードが完了しました"
LangString webview2Downloading ${LANG_JAPANESE} "WebView2 ブートストラップをダウンロード中…"
LangString webview2InstallError ${LANG_JAPANESE} "エラー: WebView2 のインストールが終了コード $1 で失敗しました。"
LangString webview2InstallSuccess ${LANG_JAPANESE} "WebView2 のインストールが完了しました"
LangString deleteAppData ${LANG_JAPANESE} "アプリケーションデータを削除する"
